go-piv/piv-go

piv-ssh-agent/go.mod, piv-ssh-agent/go.sum
Instead of pinning against a specific version of piv-go, always use the
version from the same checkout.
=> piv-ssh-agent: use a replace directive for piv-go

piv/piv.go, piv/piv_test.go
Methods should take a PIN or management key instead of having global
auth methods on the YubiKey.
=> piv: make Auth methods private

piv/key.go, piv/key_test.go
https://github.com/go-piv/piv-go/blob/master/piv/key.go#L537-L541
The `defer` calls `tx.Close()` when needed to clean up, however all of the early return paths explicitly return `nil` for `tx`, causing a nil dereference panic.  This PR has two commits, one with the test case proving the panic and the other with a fix.
Another approach could be setting `err = fmt.Errorf(...)` and just doing a bare return at the end.
=> Fix panic when k.begin() attempts to return early

piv/key.go, piv/pcsc.go, piv/pcsc_test.go, piv/piv.go, piv/piv_test.go
I got stymied not having an idiomatic way of seeing whether a smartcard object was not found or not, and I saw the TODO in the code to list error cases, so I thought I'd offer this improvement for comment.
- Promotes `apduError` to a public `ApduError` type
- Adds error messages from the latest PIV spec
- Uses error `Unwrap()` to return a few more accessible/idiomatic Go errors to enable some `errors.Is` and `errors.As` uses, such as `ErrNotFound`, `ErrBlocked`
- Promotes `errWrongPin` to `VerifyErr` type
- Changes all `%v` verbs to `%w` when wrapping errors (new in 1.13, which is what `go.mod` says we are)
- The above changes made `ykTransmit` unnecessary, so removed
I can now do things like:
```go
// Don't overwrite a slot
_, err = yk.Certificate(slot)
if err == nil {
return …
```
=> Improve error types to allow wrapping

piv/key_test.go, piv/piv_test.go
As much as possible, try to only test the public API instead of
unexported methods. We'd like to change YubiKey to hold on to a
transaction so tests should depend on being able to access this detail.
=> piv: move as many tests to the public API

piv/key.go, piv/key_test.go
Fixes #35
fyi @FiloSottile
For some reason this doesn't work:
```
% go test -v -run=TestPINPrompt . -wipe-yubikey
=== RUN   TestPINPrompt
TestPINPrompt: key_test.go:124: expected PINPrompt to only be called once got: 2
--- FAIL: TestPINPrompt (1.96s)
FAIL
FAIL    github.com/go-piv/piv-go/piv    2.253s
FAIL
```
May PINPolicyOnce still only applies to the smartcard transaction? Will investigate.
=> piv: only call PINPrompt when required

piv/key.go, piv/key_test.go
=> piv: ensure Attest returns ErrNotFound if the slot is uninitialized

piv/key.go
=> piv: document that attestation certificate must not be used for tls

piv/key.go
=> piv: use PINPolicy to determine PINPrompt strategy

piv/pcsc.go, piv/piv_test.go
Since this package holds onto a transaction, ensure other calls to Open exit immediately instead of hanging.
Updates #45
Updates #47
=> piv: mark PC/SC connection as exclusive

.github/workflows/test.yaml, Makefile, README.md, piv/pcsc.go, piv/pcsc_unix.go, piv/pcsc_windows.go
Adds support for windows via winscard. This CL leverages the
winscard api via calling into the dll. For more information
see https://docs.microsoft.com/en-us/windows/win32/api/winscard/.
Fixes #56
=> add initial windows support

piv/key.go, piv/key_test.go, piv/piv.go, piv/piv_test.go
This change:
* Introduces a fallback when creating a PrivateKey if the YubiKey
doesn't support attestation certificates.
* Fixes tests for older YubiKeys.
* Notes a bug in PIN caching for older YubiKeys.
Despite the spec[1], older YubiKeys don't let you determine if a PIN is
or isn't needed. This makes it impossible for the package to figure out
if a PIN is cached or we need to prompt. Add a BUG comment warning
against PINPolicyOnce for older YubiKeys.
[1]
https://csrc.nist.gov/CSRC/media/Publications/sp/800-73/4/archive/2015-05-29/documents/sp800_73-4_pt2_draft.pdf#page=20
Fixes #55
=> piv: fixes for older YubiKey versions

piv/key.go
This is the pull request for the issue mentioned in #62. The only change between the patch mentioned there and the one here is the renaming of `FormfactorUSBCLightning` to `FormfactorUSBCLightningKeychain` to make it fit the existing format. I'm not totally sure what the best name would be given that the device has two connectors.
Thanks!
=> piv: add yubikey 5ci form factor

piv/pcsc.go, piv/pcsc_test.go
=> piv: fix retry errors on some older yubikeys

piv/key.go, piv/key_test.go
I'm still seeing issues with my older YubiKey, but it looks like it's
not respecting the pin policy on the generated key. For example,
settings PINPolicyNone results in a "security condition not satisfied"
error.
Updates https://github.com/go-piv/piv-go/issues/60
=> piv: let user specify pin policy instead of using attestation cert

README.md, piv/pcsc_freebsd.go, piv/pcsc_unix.go
Adds files/options to build the module on FreeBSD. 
Tested on FreeBSD 12.1-RELEASE with Yubikey 4 using go test -v ./piv --wipe-yubikey command
=> Add FreeBSD support

README.md
Previously the README said this was a 'pure Go' implementation
which usually implies no cgo. Since this package wraps c libraries
(pcsc, etc.) this was a bit confusing. Remove the word 'pure'
to avoid that confusion.
=> Remove confusing word from README

piv/key.go, piv/key_test.go
Feedback on APIs would be most welcome.
Fixes #79
=> Support ECDH for ECDSA keys

piv/key.go, piv/key_test.go
This Pull Request adds constants for the Retired Key Management slots of the YubiKey 5 series. This allows the possibility of using more key slots using this library.
=> Add Retired Key Management Slots

piv/pcsc_linux.go
force go to use ulong on x32 ARCH
=> fix: overflows _Ctype_long on linux x32

piv/key.go, piv/key_test.go
Issue #77 discusses whether this library should support this feature. My use case for implementing this is to be able to create backup Yubikeys with the same private key.
Tested on: Ubuntu 20.04.1 LTS
=> Implement import key functionality

piv/key.go, piv/key_test.go
In some use cases, knowing what slot the attested key resides in
can be useful for determining whether to issue a certificate for
the key.
Signed-off-by: James Alseth <james@yubico.com>
=> Add slot name to Attestation struct

piv/key.go, piv/key_test.go
This changeset works around a manufacture bug in some 4C Nano yubikeys from the 853#### range. The PIV attestation on these yubikeys doesn't work as expected because the PIV device certificate was certified using the U2F root CA (instead of the PIV root CA). Yubico has acknowledged this issue recently in [0]. Thanks to Chris Halos from Yubico for helping root cause this.
This changeset adds the U2F root CA as an additional CA to work around this. After this PR, go-piv attestation works with both yubikeys from the lucky batch and more recent yubikeys that don't exhibit the bug.
Since testing this without a Yubikey from this series is difficult, I've added new positive and negative tests for both attestation chains.
[0] https://github.com/Yubico/developers.yubico.com/pull/392/commits/a58f100 …
=> Fix attestation manufacture bug in old yubikeys

piv/pcsc_openbsd.go, piv/pcsc_unix.go
This teaches Go where OpenBSD keeps the pcsc bits.
=> Fix build on OpenBSD

piv/key.go
I need to access the Attestation values without verifying the certificates.
I also wanted to have the option to input my own root CA instead of the one defined in this library.
I'm not sure why these should not be exposed.
=> Export ParseAttestation and Verifier struct

piv/key.go, piv/key_test.go, piv/piv.go, piv/piv_test.go
Add support for a YubiKey vendor extension to retrieve public metadata (including the public key, PIN/Touch policies and whether or not the key was hardware generated) for a given key slot.
Also use this new method to determine the pin policy, for YubiKeys that support it. This is more general than using the attestation certificate, as it also works for keys that have been generated offline and imported into the hardware token.
Fixes #129
=> piv: implement key metadata retrieval

piv/piv.go
This PR adds comments mapping the APDU being sent to the NIST Documentation.
This is very useful when updating/debugging the APDU calls being made.
=> Update ykLogin comments to reflect the NIST documentation for the commands.
